### ISSUE TITLE
Weird behavior of separators in creeper cave

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/zelda-xd2-mercuris-chess#12] opened 2017-04-02 04:45 UTC
In a cave with creepers (I don't remember which one, but I think there was a creeper face drawn on the ground), separators have weird behavior (maybe they are too close?).

**Comment by christopho** [comment] 2017-04-02 19:33
Duplicate of #1, already fixed

**Closed as completed by christopho** 2017-04-02 19:33 UTC

**Comment by Diarandor** [comment] 2017-04-02 19:35
Whoops, I didn't see it since the issue was already fixed and closed.

**Comment by christopho** [comment] 2017-04-02 19:52
No problem! :)
